-- MySQL Script generated by MySQL Workbench
-- 04/11/18 23:53:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ToDoList
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ToDoList
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ToDoList` DEFAULT CHARACTER SET utf8 ;
USE `ToDoList` ;

-- -----------------------------------------------------
-- Table `ToDoList`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToDoList`.`pessoa` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `endereco` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  PRIMARY KEY (`idpessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ToDoList`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToDoList`.`login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `fk_pessoa` INT NOT NULL,
  PRIMARY KEY (`idlogin`),
  INDEX `fk_login_pessoa_idx` (`fk_pessoa` ASC),
  CONSTRAINT `fk_login_pessoa`
    FOREIGN KEY (`fk_pessoa`)
    REFERENCES `ToDoList`.`pessoa` (`idpessoa`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ToDoList`.`tarefas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToDoList`.`tarefas` (
  `idtarefas` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `prioridade` VARCHAR(45) NOT NULL,
  `status_tarefa` VARCHAR(45) NOT NULL,
  `fk_pessoa` INT NOT NULL,
  PRIMARY KEY (`idtarefas`),
  INDEX `fk_tarefas_pessoa1_idx` (`fk_pessoa` ASC),
  CONSTRAINT `fk_tarefas_pessoa1`
    FOREIGN KEY (`fk_pessoa`)
    REFERENCES `ToDoList`.`pessoa` (`idpessoa`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
