-- MySQL Script generated by MySQL Workbench
-- 05/03/18 20:42:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ToDoList
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ToDoList
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ToDoList` DEFAULT CHARACTER SET utf8 ;
USE `ToDoList` ;

-- -----------------------------------------------------
-- Table `ToDoList`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToDoList`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `endereco` VARCHAR(45) NULL,
  `numero` VARCHAR(6) NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ToDoList`.`tarefas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToDoList`.`tarefas` (
  `idtarefas` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(90) NOT NULL,
  `data` DATE NOT NULL,
  `descricao` VARCHAR(180) NOT NULL,
  `prioridade` VARCHAR(5) NOT NULL,
  `status_tarefa` VARCHAR(13) NOT NULL,
  `fk_usuario` INT NOT NULL,
  PRIMARY KEY (`idtarefas`),
  INDEX `fk_tarefas_pessoa1_idx` (`fk_usuario` ASC),
  CONSTRAINT `fk_tarefas_pessoa1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `ToDoList`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
